# Generated by Django 5.0.2 on 2024-02-11 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lesson2', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientmodel',
            name='date_registration',
            field=models.DateField(default='2024-02-11'),
        ),
        migrations.AlterField(
            model_name='goodmodel',
            name='date_add',
            field=models.DateField(default='2024-02-11'),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='date',
            field=models.DateField(default='2024-02-11'),
        ),
    ]
