# Generated by Django 5.0.2 on 2024-02-11 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lesson2', '0002_alter_clientmodel_date_registration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodmodel',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
